TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.2
  max_vel_y: 0.3
  min_vel_y: 0.2

  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.5

  acc_lim_theta: 0.17
  acc_lim_x: 0.2
  acc_lim_y: 0.2

  holonomic_robot: true
  escape_velocity: -0.17

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2

  dwa: true

DWAPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.2
  max_vel_y: 0.3
  min_vel_y: 0.2

  max_trans_vel: 0.35
  min_trans_vel: 0.25
  max_rot_vel: 1
  min_rot_vel: -1

  acc_lim_theta: 1
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  holonomic_robot: true
  escape_velocity: -0.17

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
